version: 2
jobs:
  build:
    working_directory: ~/pillarwallet
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - run:
            name: Authenticate with Artifactory
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet/.npmrc
      - run:
            name: set Registry to use Artifactory
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Install node dependencies
          command: yarn install
      - run:
          name: Run validation
          command: yarn validate
      - run:
          name: Run unit test and generate coverage stats
          command:  yarn test:coverage
      - store_artifacts:
          path: ./reports/
          destination: reports

  publish_expo:
    working_directory: ~/pillarwallet
    docker:
      - image: circleci/node:8.9.4

    steps:
      - checkout
      - run:
          name: Install Expo cli
          command: sudo yarn global add exp
      - run:
          name: Setting .expo/PATH
          command: exp path
      - run:
            name: Authenticate with Artifactory
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet/.npmrc
      - run:
            name: set Registry to use Artifactory
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
            name: set Yarn to use Artifactory
            command: echo 'registry "https://pillarproject.jfrog.io/pillarproject/api/npm/npm/"' >> ~/pillarwallet/.yarnrc
      - run:
          name: Install node dependencies
          command: yarn install
      - run:
          name: Login to Expo
          command: exp login -u $EXPO_LOGIN -p $EXPO_PASSWORD
      - run:
          name: Publish resources bundle to Expo server
          command: exp publish

  test_ios:
    working_directory: ~/pillarwallet
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - restore_cache:
          key: node-{{ checksum "./yarn.lock" }}
      - run:
          name: Install Expo cli
          command: yarn global add exp
      - run:
          name: Setting .expo/PATH
          command: exp path
      - run:
            name: Authenticate with Artifactory
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet/.npmrc
      - run:
            name: set Registry to use Artifactory
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
            name: set Yarn to use Artifactory
            command: echo 'registry "https://pillarproject.jfrog.io/pillarproject/api/npm/npm/"' >> ~/pillarwallet/.yarnrc
      - run:
          name: Install node dependencies
          command: yarn install
      - save_cache:
          key: node-{{ checksum "./yarn.lock" }}
          paths:
            - ~/nodes_modules
      - restore_cache:
          key: pods-{{ checksum "./ios/Podfile.lock" }}
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: cd ios && pod install --verbose
      - save_cache:
          key: pods-{{ checksum "./ios/Podfile.lock" }}
          paths:
            - ./ios/Pods
      - run:
          name: Install Bundler
          command: sudo gem install bundler
      - run:
          name: Creating Gemfile in ios dir
          command: cd ios && bundle init
      - run:
          name: Login to Expo
          command: exp login -u $EXPO_LOGIN -p $EXPO_PASSWORD
      - run:
          name: Publish resources bundle to Expo server
          command: exp publish
      - run:
          name: Install fastlane gem
          command: echo 'gem "fastlane"' >> ./ios/Gemfile
      - restore_cache:
          key: gems-{{ checksum "./ios/Gemfile" }}
      - run:
          name: Create Vendor/bundle for gem dependencies
          command: cd ios && bundle check || bundle install --path vendor/bundle
      - run:
          name: Install fastlane as a dependency
          command: cd ios && sudo bundle update
      - save_cache:
          key: gems-{{ checksum "./ios/Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Execute Fastlane Build for Simulator testing
          command: cd ios && bundle exec fastlane build_ios_simulator
          environment:
            SCAN_DEVICE: iPhone 8
      - store_artifacts:
          path: ./ios/build
          destination: app_build

  deploy_ios:
    working_directory: ~/pillarwallet
    macos:
      xcode: "9.3.0"
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -o pipefail

    steps:
      - checkout
      - run:
          name: Install Expo cli
          command: yarn global add exp
      - run:
          name: Setting .expo/PATH
          command: exp path
      - restore_cache:
          key: node-{{ checksum "./yarn.lock" }}
      - run:
            name: Authenticate with Artifactory
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/pillarwallet/.npmrc
      - run:
            name: set Registry to use Artifactory
            command: npm config set registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Install node dependencies
          command: yarn install
      - save_cache:
          key: node-{{ checksum "./yarn.lock" }}
          paths:
            - ~/nodes_modules
      - restore_cache:
          key: pods-{{ checksum "./ios/Podfile.lock" }}
      - run:
          name: Fetch CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: cd ios && pod install --verbose
      - save_cache:
          key: pods-{{ checksum "./ios/Podfile.lock" }}
          paths:
            - ./ios/Pods
      - run:
          name: Install Bundler
          command: sudo gem install bundler
      - run:
          name: Creating Gemfile in ios dir
          command: cd ios && bundle init
      - run:
          name: Login to Expo
          command: exp login -u $EXPO_LOGIN -p $EXPO_PASSWORD
      - run:
          name: Publish resources bundle to Expo server
          command: exp publish
      - run:
          name: Install fastlane gem
          command: echo 'gem "fastlane"' >> ./ios/Gemfile
      - restore_cache:
          key: gems-{{ checksum "./ios/Gemfile" }}
      - run:
          name: Create Vendor/bundle for gem dependencies
          command: cd ios && bundle check || bundle install --path vendor/bundle
      - run:
          name: Install fastlane as a dependency
          command: cd ios && sudo bundle update
      - save_cache:
          key: gems-{{ checksum "./ios/Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Execute Fastlane deployment to TestFlight
          command: cd ios && bundle exec fastlane build_test_flight
          environment:
            SCAN_DEVICE: iPhone 8

  build_android:
    working_directory: ~/code/android
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      TERM: dumb
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout:
          path: ~/code
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Creating Gemfile in android dir
          command: bundle init
      - run:
          name: Install fastlane gem
          command: echo 'gem "fastlane"' >> Gemfile
      - restore_cache:
          key: gems-{{ checksum "Gemfile" }}
      - run:
          name: Bundle install
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: gems-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon --stacktrace
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.gradle
            - ~/.m2
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Initial build
          command: ./gradlew clean assembleProdRelease --no-daemon --stacktrace -PBUILD_NUMBER=$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test_ios:
          requires:
            - build
          filters:
            branches:
              only:
                  - develop
                  - master
      - deploy_ios:
          requires:
            - test_ios
          filters:
            branches:
              only: master
      - publish_expo:
          requires:
            - build
          filters:
            branches:
              only: android_fastlane_circle
      - build_android:
          requires:
            - publish_expo
          filters:
            branches:
              only: android_fastlane_circle
