name: Bump version
on:
  push:
    branches:
      - feature/git_tags_and_versioning
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@feature/git_tags_and_versioning
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true